sudo: false
language: node_js
node_js:
  - "8"
  - "10"
  - "12"
  - "14"
before_install:
  - npm install npminstall -g
install:
  - npminstall -d
script:
  - npm run ci
after_script:
  - npminstall codecov && codecov
